# This is a basic workflow to help you get started with Actions

name: CI to AWS ECR

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
    
      - name: Check Out Repo 
        uses: actions/checkout@v2
      - name: Docker ECR
        # You may pin to the exact commit or the version.
        # uses: appleboy/docker-ecr-action@174bc7ab545bf5c4f4492240c4d839a987643559
        uses: appleboy/docker-ecr-action@v0.0.3
        with:
          # amazon access key
          access_key: AKIAUUTSLL7EWTKC4ZVM
          # amazon secret access key
          secret_key: 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
          # docker registry
          registry: http://319141142473.dkr.ecr.ap-south-1.amazonaws.com
          # amazon region, defaults to us-east-1
          region: ap-south-1
          # repository name for the image
          repo: github-action-deploy
          # repository tag for the image, defaults to latest
          #tags: github-deployed
          # dockerfile to be used, defaults to Dockerfile
          #dockerfile: # optional, default is Dockerfile
          # do not start the docker daemon
          daemon_off: false
