# This is a basic workflow to help you get started with Actions

name: CI to AWS ECR

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
    
      - name: Check Out Repo 
        uses: actions/checkout@v2

      - name: Push AWS ECR
        # You may pin to the exact commit or the version.
        # uses: hands-lab/push-ecr-action@18f19e41550f632ff0d8ce224a3ffd1e552d3598
        uses: hands-lab/push-ecr-action@v1.1
        with:
          # image name
          image: leo-electricals
          # AWS Access Key ID
          aws-access-key-id: AKIAUUTSLL7EWTKC4ZVM 
          # AWS Secret Access Key
          aws-secret-access-key: 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 
          # AWS Region
          aws-region: ap-south-1
          # AWS Account ID
          aws-account-id: mkd63   

